#!/usr/bin/env node

import { chmod, copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build as esbuild } from "esbuild";
import { build as viteBuild } from "vite";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const uiOutput = path.join(root, "skills/utsuri-review/assets/report-ui");
const generatedUi = path.join(root, "packages/report-builder/src/generated-ui-assets.ts");
const cliOutput = path.join(root, "packages/cli/dist/utsuri.mjs");
const skillCliOutput = path.join(root, "skills/utsuri-review/scripts/utsuri.mjs");
const cliPackageRoot = path.join(root, "packages/cli");

await import("./build-native-helper.mjs");
await viteBuild({ configFile: path.join(root, "vite.config.ts") });
const appJavaScript = await readFile(path.join(uiOutput, "app.js"), "utf8");
const appCss = await readFile(path.join(uiOutput, "app.css"), "utf8");
await writeFile(
  generatedUi,
  `/* Generated by scripts/build.mjs. */\nexport const reportUiJavaScript = ${JSON.stringify(appJavaScript)};\nexport const reportUiCss = ${JSON.stringify(appCss)};\n`
);

await mkdir(path.dirname(cliOutput), { recursive: true });
await mkdir(path.dirname(skillCliOutput), { recursive: true });
await esbuild({
  entryPoints: [path.join(root, "packages/cli/src/main.ts")],
  outfile: cliOutput,
  banner: {
    js: '#!/usr/bin/env node\nimport { createRequire as __utsuriCreateRequire } from "node:module";\nconst require = __utsuriCreateRequire(import.meta.url);'
  },
  bundle: true,
  charset: "utf8",
  format: "esm",
  legalComments: "none",
  logLevel: "warning",
  minify: false,
  platform: "node",
  target: "node22"
});
await chmod(cliOutput, 0o755);
await copyFile(cliOutput, skillCliOutput);
await chmod(skillCliOutput, 0o755);

await Promise.all([
  copyFile(path.join(root, "README.md"), path.join(cliPackageRoot, "README.md")),
  copyFile(path.join(root, "LICENSE"), path.join(cliPackageRoot, "LICENSE"))
]);

const schemaOutput = path.join(root, "skills/utsuri-review/schemas");
await mkdir(schemaOutput, { recursive: true });
for (const name of [
  "annotations.schema.json",
  "config.schema.json",
  "context-pack.schema.json",
  "feedback-batch.schema.json",
  "origin-session.schema.json",
  "report.schema.json",
  "review-answer.schema.json",
  "review-state.schema.json",
  "review-thread.schema.json"
]) {
  await copyFile(path.join(root, "schemas", name), path.join(schemaOutput, name));
}

console.log(
  "Built Node 22 ESM CLI, native helper, Svelte report UI, package metadata, and release schema copies"
);
